version: "3"

services:
  bot:
    build: .
    container_name: bot
    command: python3 app.py
    env_file: ./.env
    volumes:
      - .:/app
    depends_on:
      - db

  admin:
    command: python3 manage.py runserver 0.0.0.0:8000
    container_name: admin
    build: .
    volumes:
      - .:/app
    ports:
      - "80:8000"
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres:14
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
