# Generated by Django 5.0.4 on 2024-05-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselmainphoto',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carouselmainphoto',
            name='description_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carouselmainphoto',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carouselmainphoto',
            name='description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carouselmainphoto',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carouselmainphoto',
            name='description_zh_hans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carouselmainphoto',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carouselmainphoto',
            name='name_kk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carouselmainphoto',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carouselmainphoto',
            name='name_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carouselmainphoto',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carouselmainphoto',
            name='name_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoryled',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoryled',
            name='name_kk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoryled',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoryled',
            name='name_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoryled',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoryled',
            name='name_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categorywallpaper',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categorywallpaper',
            name='name_kk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categorywallpaper',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categorywallpaper',
            name='name_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categorywallpaper',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categorywallpaper',
            name='name_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leds',
            name='description_en',
            field=models.TextField(blank=True, default='Led', null=True),
        ),
        migrations.AddField(
            model_name='leds',
            name='description_kk',
            field=models.TextField(blank=True, default='Led', null=True),
        ),
        migrations.AddField(
            model_name='leds',
            name='description_ru',
            field=models.TextField(blank=True, default='Led', null=True),
        ),
        migrations.AddField(
            model_name='leds',
            name='description_tr',
            field=models.TextField(blank=True, default='Led', null=True),
        ),
        migrations.AddField(
            model_name='leds',
            name='description_uz',
            field=models.TextField(blank=True, default='Led', null=True),
        ),
        migrations.AddField(
            model_name='leds',
            name='description_zh_hans',
            field=models.TextField(blank=True, default='Led', null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_kk',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_tr',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_uz',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_zh_hans',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_kk',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_tr',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_zh_hans',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, default='Make your life easier with our services.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_kk',
            field=models.TextField(blank=True, default='Make your life easier with our services.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(blank=True, default='Make your life easier with our services.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_tr',
            field=models.TextField(blank=True, default='Make your life easier with our services.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_uz',
            field=models.TextField(blank=True, default='Make your life easier with our services.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_zh_hans',
            field=models.TextField(blank=True, default='Make your life easier with our services.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_kk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='description_en',
            field=models.TextField(default='Worker at the company', null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='description_kk',
            field=models.TextField(default='Worker at the company', null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='description_ru',
            field=models.TextField(default='Worker at the company', null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='description_tr',
            field=models.TextField(default='Worker at the company', null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='description_uz',
            field=models.TextField(default='Worker at the company', null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='description_zh_hans',
            field=models.TextField(default='Worker at the company', null=True),
        ),
        migrations.AddField(
            model_name='wallcovers',
            name='description_en',
            field=models.TextField(blank=True, default='Wallcover', null=True),
        ),
        migrations.AddField(
            model_name='wallcovers',
            name='description_kk',
            field=models.TextField(blank=True, default='Wallcover', null=True),
        ),
        migrations.AddField(
            model_name='wallcovers',
            name='description_ru',
            field=models.TextField(blank=True, default='Wallcover', null=True),
        ),
        migrations.AddField(
            model_name='wallcovers',
            name='description_tr',
            field=models.TextField(blank=True, default='Wallcover', null=True),
        ),
        migrations.AddField(
            model_name='wallcovers',
            name='description_uz',
            field=models.TextField(blank=True, default='Wallcover', null=True),
        ),
        migrations.AddField(
            model_name='wallcovers',
            name='description_zh_hans',
            field=models.TextField(blank=True, default='Wallcover', null=True),
        ),
    ]
