# Generated by Django 5.0.4 on 2024-04-29 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orm_app.sale'),
        ),
        migrations.DeleteModel(
            name='SaleReview',
        ),
    ]
