# Generated by Django 5.0.4 on 2024-05-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0002_review_sale_delete_salereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(related_name='users', to='orm_app.organization'),
        ),
    ]
