# Generated by Django 5.0.4 on 2024-05-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0003_rename_image_product_image1_product_image2'),
        ('orm_app', '0003_user_organizations'),
    ]

    operations = [
    ]
