# Generated by Django 5.0.4 on 2024-05-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0004_merge_20240519_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(),
        ),
    ]
