# Generated by Django 5.0.4 on 2024-05-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0005_alter_user_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('telegram_id', models.BigIntegerField()),
                ('phone_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
